name: app

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub 
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/images:app-${{ github.run_number }}

  modify-manifests:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kubernetes Manifests
      uses: actions/checkout@v2
      with: 
        repository: ${{ secrets.GIT_USERNAME }}/manifest_k8
        token: ${{ secrets.GIT_PASSWORD }}

    - name: Update image tag in manifests
      run: |
        pwd
        sed -i "s+${{ secrets.DOCKERHUB_USERNAME }}/images.*+${{ secrets.DOCKERHUB_USERNAME }}/images:app${{ github.run_number }}+g" deployment.yaml
        cat deployment.yaml

    - name: Commit and push changes  
      run: |
        git config user.email jjgp2903@gmail.com
        git config user.name Botali2903
        git add .
        if git diff --cached --exit-code; then
          echo "No change to commit"
        else 
          git commit -m "Updated image tag to ${{ github.run_number }}"
          git push origin main  
        fi
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        RUN_NUMBER: ${{ github.run_number }}
